language: node_js
node_js:
  - "4.2"
sudo: true
cache:
  directories:
    - node_modules
    - core/client/node_modules
    - core/client/bower_components
before_script:
  - npm install -g grunt-cli
script:
  - npm install
  - grunt init
  - grunt prod
after_success:
  if [ ! -z "$TRAVIS_TAG" ]; then
    grunt release
    ls -a dist-folder/*/
  fi
deploy:
  provider: releases
  api_key:
      secure: "2o5I2VHY5neNfi51zYsEFyrfMZbjzAgjvai3w0POfL+8S/vM1/Ov0EiLViwZMl77flzxFHBbqJjJy4HZ4gHGEvHhmywS3YjBnNbp6OnIwof7DGsTVtuV2DIwr/VjUrXvrkdNEbhltuhkAFERXaMyx28wnnRIwT78tHs+iWEvt32uHmhghy6qR5qKZn3vtxft0ycRs3n2H2zhpGen4ubz23VpfeH9z09c0C0FBIATCLvtOMIBzHQWMaZ+e3DF6kGUOJWbsWu+YK7hUStElH8SP6hiHgAkBBYipQW1vDhX/6VSV1tfqd+mpbHc1hNE8tgDOvfdA26PrhLbj45Bqom7Ofsm3oxzBpQRWcR9WGdanyqh4YMo1E50Ock2QDvyXvBWNKlQpmdsAUgG3Kb6jZfW5S8e81enTSdD8OpNIWmH/8A3BUsHLZvtRaV5qKVM3KmYjgC3K6SutTUa51XdpEz+Tr51gpDmIrHigowegUCby3yRTY8zFGFKjEEk2Sz4mVAOonsdEw7E0NhVQzneS1NnETytZsPADPN6MIDDip9/3hNJ9lgXEQLSX0Gsr0dyfgkfadoQXY9SrMo/Hk5s1iPEuNCM6axxw4ErdjKGOnjt++0UxfB7aQWMn56lm8iKDF6SfHcRtv9+KwgvA12/4aN/e0gB367HEd613a1nmM+DffU="
  file: dist-folder/*/*.zip
  skip_cleanup: true
  on:
    tags: true
